namespace FEZAnalyzer.Entity
{
    public class FezGlobalSetting
    {
        public int? ScreenWidth { get; set; }
        public int? ScreenHeight { get; set; }
        public int? Fullscreen { get; set; }
        public int? SoundEnable { get; set; }
        public int? ReflectEnable { get; set; }
        public int? ReflectLevel { get; set; }
        public int? ShadowLevel { get; set; }
        public int? BgmVolume { get; set; }
        public int? BgmAlbum { get; set; }
        public int? BgmVersion { get; set; }
        public int? SeVolume { get; set; }
        public int? Gamma { get; set; }
        public int? FarClip { get; set; }
        public int? InputMode { get; set; }
        public int? MouseSensitivity { get; set; }
        public int? CameraReverseVertical { get; set; }
        public int? CameraReverseHorizon { get; set; }
        public int? OpeningMovie { get; set; }
        public int? TextureResolution { get; set; }
        public int? CharaInfo { get; set; }
        public int? HpBar { get; set; }
        public int? CharaName { get; set; }
        public int? ForceName { get; set; }
        public int? Icons { get; set; }
        public int? SkillInfo { get; set; }
        public int? DoubleKeyStep { get; set; }
        public int? DispCharacterNum { get; set; }
        public int? DispStageEffect { get; set; }
        public int? DispItemEffect { get; set; }
        public int? ActiveLog { get; set; }
        public int? DispChatSay { get; set; }
        public int? DispChatAll { get; set; }
        public int? DispChatArmy { get; set; }
        public int? DispChatArmySay { get; set; }
        public int? DispChatWhisper { get; set; }
        public int? DispChatParty { get; set; }
        public int? DispChatLeader { get; set; }
        public int? DispChatEmotion { get; set; }
        public int? DispChatBalloon { get; set; }
        public int? DispChatSystem { get; set; }
        public int? DispChatBattleFriend { get; set; }
        public int? DispChatBattleEnemy { get; set; }
        public int? DispChatBattleEtc { get; set; }
        public int? DispWarSituationInfo { get; set; }
        public int? PartyInvitePermit { get; set; }
        public int? GuildInvitePermit { get; set; }
        public int? TradeInvitePermit { get; set; }
        public int? DispLogLines { get; set; }
        public int? WorldDispLogLines { get; set; }
        public int? WindowColor { get; set; }
        public float? CameraRadiusRate { get; set; }
        public int? DispChatLog { get; set; }
        public int? WorldDispChatLog { get; set; }
        public int? DispUpBattleLog { get; set; }
        public int? AutoLogEnable { get; set; }
        public int? ColorChatSay { get; set; }
        public int? ColorChatAll { get; set; }
        public int? ColorChatArmy { get; set; }
        public int? ColorChatArmySay { get; set; }
        public int? ColorChatWhisper { get; set; }
        public int? ColorChatParty { get; set; }
        public int? ColorChatLeader { get; set; }
        public int? ColorChatEmotion { get; set; }
        public int? RadarMapEdgeEnable { get; set; }
        public int? BuildingAlertDisp { get; set; }
        public int? BuildingAlertColorDisp { get; set; }
        public int? BallistaEdgeEnable { get; set; }
        public int? PlayVoiceType { get; set; }
        public int? PlayKingVoiceEnable { get; set; }
        public int? VoiceVolume { get; set; }
        public int? CameraInterfaceMode { get; set; }
        public int? FpsLimit { get; set; }
        public int? NpcName { get; set; }
        public int? PartyDirection { get; set; }
        public int? AutochangeChattype { get; set; }
        public int? MapRotateMode { get; set; }
        public int? MapSmoothMode { get; set; }
        public int? ReplayAutoSave { get; set; }
        public int? BestRankCategory { get; set; }
        public int? WindowEditMode { get; set; }
        public int? SkillTreeRow { get; set; }
        public int? ItemSortOrder { get; set; }
        public int? InventorySortOrder { get; set; }
        public int? FootprintType { get; set; }
        public int? MiniMapMode { get; set; }
        public int? MiniMapPosX { get; set; }
        public int? MiniMapPosY { get; set; }
        public int? MiniMapZoom { get; set; }
        public int? MiniMapSize { get; set; }
        public int? MiniMapAlpha { get; set; }
        public int? SummonCountOpen { get; set; }
        public int? SummonCountPosX { get; set; }
        public int? SummonCountPosY { get; set; }
        public int? SummonCountDispType { get; set; }
        public int? SummonCountGripType { get; set; }
        public int? SummonCountGripWindow { get; set; }
        public int? SummonCountGripOffsetX { get; set; }
        public int? SummonCountGripOffsetY { get; set; }
        public int? DispDraweffectitem { get; set; }
        public int? DispScoreDetailInfo { get; set; }
        public int? DispHighModel { get; set; }
        public int? DispPingWarningAlert { get; set; }
    }
}
